### ISSUE TITLE
IGDM issue when I type 3 dots "..."

### ISSUE THREAD

**Issue by greenhalgh** [ifedapoolarewaju/igdm#1040]
Not sure if its a bug, or a secret thing. I tend to use three dots, in place of punctuation. Yeah its a habit...but, when I do I get random pics pop up in IGDM. LAtely its a 2017 picture of Jeffrey Epstein.
![Capture20190812](https://user-images.githubusercontent.com/3137981/62904632-2305a680-bd35-11e9-9682-258fb6bde370.JPG)

**Comment by ifedapoolarewaju** [comment]
this issue is now fixed in the latest version

**Comment by jonstraveladventures** [comment]
I've just downloaded the latest version using git clone https://github.com/ifedapoolarewaju/igdm.git and it is still occurring.
