### ISSUE TITLE
Loading more messages on scroll

### ISSUE THREAD

**Issue by solomon-fibonacci** [ifedapoolarewaju/igdm#13]
Limited amount of messages are currently being loaded per chat. Would be nice to implement the feature to load more messages are users scroll up their chat.

**Comment by thedexterouz** [comment]
I am on version **"Version 2.4.1"**, but the issue persists. It doesn't load previous chats.
When can it be solved? Thanks.
 
#39 Will redirect to this #13  :|

**Comment by ifedapoolarewaju** [comment]
this issue is fixed on the version 2.5.1 please visit the site http://igdm.me to download the latest version

**Comment by baptx** [comment]
@ifedapoolarewaju is the fix about the limit in the number of messages with another user or about the limit in the number of conversations that can be displayed?
We still can't see all conversations history in the version 2.5.1 (it is limited to the last 20 users), I tested on Linux (Xubuntu) with the file that was shared here: https://github.com/ifedapoolarewaju/igdm/issues/349#issuecomment-396568474
I guess this issue should be reopened if it is about the conversations history limit, otherwise another issue should be created.
By the way, is it not possible to delete a message or a conversation? If there is an Instagram API for this, the feature could be added.
